# Generated by Django 3.0.5 on 2021-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_registeration_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeration',
            name='time',
        ),
        migrations.AddField(
            model_name='registeration',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registeration',
            name='programme',
            field=models.CharField(default='programme', max_length=255),
        ),
    ]
