# Generated by Django 3.0.5 on 2021-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20211113_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='studentplaced',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='studentplaced',
            name='role',
            field=models.CharField(default='role', max_length=255),
        ),
        migrations.AddField(
            model_name='studentplaced',
            name='rollno',
            field=models.CharField(default='rollno', max_length=100),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
