# Generated by Django 3.0.5 on 2021-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_auto_20211115_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplaced',
            name='image',
            field=models.FileField(default='defaults.jpg', upload_to=''),
        ),
    ]
